#!/bin/sh

set -e
echo IFACE=$IFACE
echo IP_ADDRS=$IP_ADDRS
echo STATE=$STATE

[ "$IFACE" = "en000rtk" ] || exit 0
[ "$STATE" = "routable" ] || exit 0
[ -n "$IP_ADDRS" ] || exit 0
LC_ALL=en_US.UTF-8; export LC_ALL
sudo -u monter /bin/bash -c 'sleep 5 && cd /home/monter/TEST && ./jtest.sh 2>&1 1>/dev/null'
exit 0
